name: Setup Gradle
description: Sets up the environment to run Gradle

runs:
  using: composite

  steps:
    - name: Write Gradle build properties to `~/.gradle/gradle.properties`
      run: |
        mkdir -p ~/.gradle
        printf "org.gradle.jvmargs=-Xmx3G -XX:+UseParallelGC\n" >> ~/.gradle/gradle.properties
        printf "org.gradle.vfs.watch=false\n" >> ~/.gradle/gradle.properties
      shell: bash

    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 24

    - uses: gradle/actions/wrapper-validation@v4

    - uses: gradle/actions/setup-gradle@v4
