name: Build Project

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    name: '[${{ matrix.os }}] build plugin'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: gradle/actions/wrapper-validation@v5

      - uses: ./.github/actions/setup-gradle-build

      - run: ./gradlew assemble

      - run: ./gradlew check

      - run: ./gradlew publishToMavenLocal

      - run: ./gradlew publishPlugins -m

      - run: git diff --exit-code

      - uses: actions/upload-artifact@v5
        if: ${{ always() }}
        with:
          name: test-results-${{ matrix.os }}
          path: "${{ github.workspace }}/**/build/reports/tests"
